### ISSUE TITLE
Unclean leader election defaults to true

### ISSUE THREAD

**Issue by rcillo** [zalando/saiki-buku#48]
Kafka default value for `unclean.leader.election.enable` is `true`. By the documentation

> Indicates whether to enable replicas not in the ISR set to be elected as leader as a last resort, even though doing so may result in data loss

That could lead to data loss, as explained in this slide from Kafka developers presentation http://www.slideshare.net/ConfluentInc/when-it-absolutely-positively-has-to-be-there-reliability-guarantees-in-kafka-gwen-shapira-jeff-holoman/17?src=clipshare

Some clusters might prioritise data safety over availability.

Do you think it would be useful to add a feature to customize `server.properties` file? If so, do you have any suggestions on how to implement it? I could open a PR with that.

**Comment by chutium** [comment]
customizing config files is already supported, take a look https://github.com/zalando/saiki-buku/issues/46#issuecomment-217424181

it is implemented here: https://github.com/zalando/saiki-buku/blob/79f1244333b28683ea603d005815b47127baa23a/src/start_kafka_and_reassign_partitions.py#L39

due to code reorganisations, code history are gone :(

**Comment by drummerwolli** [comment]
@rcillo is this env variables assignment sufficient for you?

**Comment by rcillo** [comment]
Thank you  @chutium and @drummerwolli this is just perfect 👍
